// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ActiveTrustedKeyGroupsInitParameters struct {

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	Items []ActiveTrustedKeyGroupsItemsInitParameters `json:"items,omitempty" tf:"items,omitempty"`
}

type ActiveTrustedKeyGroupsItemsInitParameters struct {
}

type ActiveTrustedKeyGroupsItemsObservation struct {

	// ID of the key group that contains the public keys.
	KeyGroupID *string `json:"keyGroupId,omitempty" tf:"key_group_id,omitempty"`

	// Set of active CloudFront key pairs associated with the signer that can be used to verify the signatures of signed URLs and signed cookies.
	KeyPairIds []*string `json:"keyPairIds,omitempty" tf:"key_pair_ids,omitempty"`
}

type ActiveTrustedKeyGroupsItemsParameters struct {
}

type ActiveTrustedKeyGroupsObservation struct {

	// Whether the distribution is enabled to accept end user requests for content.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	Items []ActiveTrustedKeyGroupsItemsObservation `json:"items,omitempty" tf:"items,omitempty"`
}

type ActiveTrustedKeyGroupsParameters struct {

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	// +kubebuilder:validation:Optional
	Items []ActiveTrustedKeyGroupsItemsParameters `json:"items,omitempty" tf:"items,omitempty"`
}

type AllowedMethodsInitParameters struct {

	// Controls whether CloudFront caches the response to requests using the specified HTTP methods.
	// +listType=set
	CachedMethods []*string `json:"cachedMethods,omitempty" tf:"cached_methods,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	// +listType=set
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`
}

type AllowedMethodsObservation struct {

	// Controls whether CloudFront caches the response to requests using the specified HTTP methods.
	// +listType=set
	CachedMethods []*string `json:"cachedMethods,omitempty" tf:"cached_methods,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	// +listType=set
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`
}

type AllowedMethodsParameters struct {

	// Controls whether CloudFront caches the response to requests using the specified HTTP methods.
	// +kubebuilder:validation:Optional
	// +listType=set
	CachedMethods []*string `json:"cachedMethods" tf:"cached_methods,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	// +kubebuilder:validation:Optional
	// +listType=set
	Items []*string `json:"items" tf:"items,omitempty"`
}

type CacheBehaviorFunctionAssociationInitParameters struct {

	// Specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response.
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// ARN of the CloudFront function.
	FunctionArn *string `json:"functionArn,omitempty" tf:"function_arn,omitempty"`
}

type CacheBehaviorFunctionAssociationObservation struct {

	// Specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response.
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// ARN of the CloudFront function.
	FunctionArn *string `json:"functionArn,omitempty" tf:"function_arn,omitempty"`
}

type CacheBehaviorFunctionAssociationParameters struct {

	// Specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response.
	// +kubebuilder:validation:Optional
	EventType *string `json:"eventType" tf:"event_type,omitempty"`

	// ARN of the CloudFront function.
	// +kubebuilder:validation:Optional
	FunctionArn *string `json:"functionArn" tf:"function_arn,omitempty"`
}

type CacheBehaviorInitParameters struct {

	// Controls which HTTP methods CloudFront processes and forwards to your Amazon S3 bucket or your custom origin.
	AllowedMethods []AllowedMethodsInitParameters `json:"allowedMethods,omitempty" tf:"allowed_methods,omitempty"`

	// Unique identifier of the cache policy that is attached to the cache behavior.
	CachePolicyID *string `json:"cachePolicyId,omitempty" tf:"cache_policy_id,omitempty"`

	// Whether you want CloudFront to automatically compress content for web requests that include Accept-Encoding: gzip in the request header. Default: false.
	Compress *bool `json:"compress,omitempty" tf:"compress,omitempty"`

	// Field level encryption configuration ID.
	FieldLevelEncryptionID *string `json:"fieldLevelEncryptionId,omitempty" tf:"field_level_encryption_id,omitempty"`

	// Configuration block for CloudFront Functions associations. See Function Association below.
	FunctionAssociation []CacheBehaviorFunctionAssociationInitParameters `json:"functionAssociation,omitempty" tf:"function_association,omitempty"`

	// Configuration block for Lambda@Edge associations. See Lambda Function Association below.
	LambdaFunctionAssociation []CacheBehaviorLambdaFunctionAssociationInitParameters `json:"lambdaFunctionAssociation,omitempty" tf:"lambda_function_association,omitempty"`

	// Unique identifier of the origin request policy that is attached to the behavior.
	OriginRequestPolicyID *string `json:"originRequestPolicyId,omitempty" tf:"origin_request_policy_id,omitempty"`

	// Pattern that specifies which requests you want this cache behavior to apply to.
	PathPattern *string `json:"pathPattern,omitempty" tf:"path_pattern,omitempty"`

	// ARN of the real-time log configuration that is attached to this cache behavior.
	RealtimeLogConfigArn *string `json:"realtimeLogConfigArn,omitempty" tf:"realtime_log_config_arn,omitempty"`

	// Identifier for a response headers policy.
	ResponseHeadersPolicyID *string `json:"responseHeadersPolicyId,omitempty" tf:"response_headers_policy_id,omitempty"`

	// Value of ID for the origin that you want CloudFront to route requests to when a request matches the path pattern either for a cache behavior or for the default cache behavior.
	TargetOriginID *string `json:"targetOriginId,omitempty" tf:"target_origin_id,omitempty"`

	// List of key group IDs that CloudFront can use to validate signed URLs or signed cookies.
	TrustedKeyGroups []CacheBehaviorTrustedKeyGroupsInitParameters `json:"trustedKeyGroups,omitempty" tf:"trusted_key_groups,omitempty"`

	// Use this element to specify the protocol that users can use to access the files in the origin specified by TargetOriginId when a request matches the path pattern in PathPattern. One of allow-all, https-only, or redirect-to-https.
	ViewerProtocolPolicy *string `json:"viewerProtocolPolicy,omitempty" tf:"viewer_protocol_policy,omitempty"`
}

type CacheBehaviorLambdaFunctionAssociationInitParameters struct {

	// Specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response.
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// When set to true, the request body is exposed to the Lambda function. Default: false.
	IncludeBody *bool `json:"includeBody,omitempty" tf:"include_body,omitempty"`

	// ARN of the Lambda function.
	LambdaFunctionArn *string `json:"lambdaFunctionArn,omitempty" tf:"lambda_function_arn,omitempty"`
}

type CacheBehaviorLambdaFunctionAssociationObservation struct {

	// Specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response.
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// When set to true, the request body is exposed to the Lambda function. Default: false.
	IncludeBody *bool `json:"includeBody,omitempty" tf:"include_body,omitempty"`

	// ARN of the Lambda function.
	LambdaFunctionArn *string `json:"lambdaFunctionArn,omitempty" tf:"lambda_function_arn,omitempty"`
}

type CacheBehaviorLambdaFunctionAssociationParameters struct {

	// Specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response.
	// +kubebuilder:validation:Optional
	EventType *string `json:"eventType" tf:"event_type,omitempty"`

	// When set to true, the request body is exposed to the Lambda function. Default: false.
	// +kubebuilder:validation:Optional
	IncludeBody *bool `json:"includeBody,omitempty" tf:"include_body,omitempty"`

	// ARN of the Lambda function.
	// +kubebuilder:validation:Optional
	LambdaFunctionArn *string `json:"lambdaFunctionArn" tf:"lambda_function_arn,omitempty"`
}

type CacheBehaviorObservation struct {

	// Controls which HTTP methods CloudFront processes and forwards to your Amazon S3 bucket or your custom origin.
	AllowedMethods []AllowedMethodsObservation `json:"allowedMethods,omitempty" tf:"allowed_methods,omitempty"`

	// Unique identifier of the cache policy that is attached to the cache behavior.
	CachePolicyID *string `json:"cachePolicyId,omitempty" tf:"cache_policy_id,omitempty"`

	// Whether you want CloudFront to automatically compress content for web requests that include Accept-Encoding: gzip in the request header. Default: false.
	Compress *bool `json:"compress,omitempty" tf:"compress,omitempty"`

	// Field level encryption configuration ID.
	FieldLevelEncryptionID *string `json:"fieldLevelEncryptionId,omitempty" tf:"field_level_encryption_id,omitempty"`

	// Configuration block for CloudFront Functions associations. See Function Association below.
	FunctionAssociation []CacheBehaviorFunctionAssociationObservation `json:"functionAssociation,omitempty" tf:"function_association,omitempty"`

	// Configuration block for Lambda@Edge associations. See Lambda Function Association below.
	LambdaFunctionAssociation []CacheBehaviorLambdaFunctionAssociationObservation `json:"lambdaFunctionAssociation,omitempty" tf:"lambda_function_association,omitempty"`

	// Unique identifier of the origin request policy that is attached to the behavior.
	OriginRequestPolicyID *string `json:"originRequestPolicyId,omitempty" tf:"origin_request_policy_id,omitempty"`

	// Pattern that specifies which requests you want this cache behavior to apply to.
	PathPattern *string `json:"pathPattern,omitempty" tf:"path_pattern,omitempty"`

	// ARN of the real-time log configuration that is attached to this cache behavior.
	RealtimeLogConfigArn *string `json:"realtimeLogConfigArn,omitempty" tf:"realtime_log_config_arn,omitempty"`

	// Identifier for a response headers policy.
	ResponseHeadersPolicyID *string `json:"responseHeadersPolicyId,omitempty" tf:"response_headers_policy_id,omitempty"`

	// Value of ID for the origin that you want CloudFront to route requests to when a request matches the path pattern either for a cache behavior or for the default cache behavior.
	TargetOriginID *string `json:"targetOriginId,omitempty" tf:"target_origin_id,omitempty"`

	// List of key group IDs that CloudFront can use to validate signed URLs or signed cookies.
	TrustedKeyGroups []CacheBehaviorTrustedKeyGroupsObservation `json:"trustedKeyGroups,omitempty" tf:"trusted_key_groups,omitempty"`

	// Use this element to specify the protocol that users can use to access the files in the origin specified by TargetOriginId when a request matches the path pattern in PathPattern. One of allow-all, https-only, or redirect-to-https.
	ViewerProtocolPolicy *string `json:"viewerProtocolPolicy,omitempty" tf:"viewer_protocol_policy,omitempty"`
}

type CacheBehaviorParameters struct {

	// Controls which HTTP methods CloudFront processes and forwards to your Amazon S3 bucket or your custom origin.
	// +kubebuilder:validation:Optional
	AllowedMethods []AllowedMethodsParameters `json:"allowedMethods,omitempty" tf:"allowed_methods,omitempty"`

	// Unique identifier of the cache policy that is attached to the cache behavior.
	// +kubebuilder:validation:Optional
	CachePolicyID *string `json:"cachePolicyId,omitempty" tf:"cache_policy_id,omitempty"`

	// Whether you want CloudFront to automatically compress content for web requests that include Accept-Encoding: gzip in the request header. Default: false.
	// +kubebuilder:validation:Optional
	Compress *bool `json:"compress,omitempty" tf:"compress,omitempty"`

	// Field level encryption configuration ID.
	// +kubebuilder:validation:Optional
	FieldLevelEncryptionID *string `json:"fieldLevelEncryptionId,omitempty" tf:"field_level_encryption_id,omitempty"`

	// Configuration block for CloudFront Functions associations. See Function Association below.
	// +kubebuilder:validation:Optional
	FunctionAssociation []CacheBehaviorFunctionAssociationParameters `json:"functionAssociation,omitempty" tf:"function_association,omitempty"`

	// Configuration block for Lambda@Edge associations. See Lambda Function Association below.
	// +kubebuilder:validation:Optional
	LambdaFunctionAssociation []CacheBehaviorLambdaFunctionAssociationParameters `json:"lambdaFunctionAssociation,omitempty" tf:"lambda_function_association,omitempty"`

	// Unique identifier of the origin request policy that is attached to the behavior.
	// +kubebuilder:validation:Optional
	OriginRequestPolicyID *string `json:"originRequestPolicyId,omitempty" tf:"origin_request_policy_id,omitempty"`

	// Pattern that specifies which requests you want this cache behavior to apply to.
	// +kubebuilder:validation:Optional
	PathPattern *string `json:"pathPattern" tf:"path_pattern,omitempty"`

	// ARN of the real-time log configuration that is attached to this cache behavior.
	// +kubebuilder:validation:Optional
	RealtimeLogConfigArn *string `json:"realtimeLogConfigArn,omitempty" tf:"realtime_log_config_arn,omitempty"`

	// Identifier for a response headers policy.
	// +kubebuilder:validation:Optional
	ResponseHeadersPolicyID *string `json:"responseHeadersPolicyId,omitempty" tf:"response_headers_policy_id,omitempty"`

	// Value of ID for the origin that you want CloudFront to route requests to when a request matches the path pattern either for a cache behavior or for the default cache behavior.
	// +kubebuilder:validation:Optional
	TargetOriginID *string `json:"targetOriginId" tf:"target_origin_id,omitempty"`

	// List of key group IDs that CloudFront can use to validate signed URLs or signed cookies.
	// +kubebuilder:validation:Optional
	TrustedKeyGroups []CacheBehaviorTrustedKeyGroupsParameters `json:"trustedKeyGroups,omitempty" tf:"trusted_key_groups,omitempty"`

	// Use this element to specify the protocol that users can use to access the files in the origin specified by TargetOriginId when a request matches the path pattern in PathPattern. One of allow-all, https-only, or redirect-to-https.
	// +kubebuilder:validation:Optional
	ViewerProtocolPolicy *string `json:"viewerProtocolPolicy" tf:"viewer_protocol_policy,omitempty"`
}

type CacheBehaviorTrustedKeyGroupsInitParameters struct {

	// Whether the distribution is enabled to accept end user requests for content.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`
}

type CacheBehaviorTrustedKeyGroupsObservation struct {

	// Whether the distribution is enabled to accept end user requests for content.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`
}

type CacheBehaviorTrustedKeyGroupsParameters struct {

	// Whether the distribution is enabled to accept end user requests for content.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	// +kubebuilder:validation:Optional
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`
}

type DefaultCacheBehaviorAllowedMethodsInitParameters struct {

	// Controls whether CloudFront caches the response to requests using the specified HTTP methods.
	// +listType=set
	CachedMethods []*string `json:"cachedMethods,omitempty" tf:"cached_methods,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	// +listType=set
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`
}

type DefaultCacheBehaviorAllowedMethodsObservation struct {

	// Controls whether CloudFront caches the response to requests using the specified HTTP methods.
	// +listType=set
	CachedMethods []*string `json:"cachedMethods,omitempty" tf:"cached_methods,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	// +listType=set
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`
}

type DefaultCacheBehaviorAllowedMethodsParameters struct {

	// Controls whether CloudFront caches the response to requests using the specified HTTP methods.
	// +kubebuilder:validation:Optional
	// +listType=set
	CachedMethods []*string `json:"cachedMethods" tf:"cached_methods,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	// +kubebuilder:validation:Optional
	// +listType=set
	Items []*string `json:"items" tf:"items,omitempty"`
}

type DefaultCacheBehaviorFunctionAssociationInitParameters struct {

	// Specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response.
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// ARN of the CloudFront function.
	FunctionArn *string `json:"functionArn,omitempty" tf:"function_arn,omitempty"`
}

type DefaultCacheBehaviorFunctionAssociationObservation struct {

	// Specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response.
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// ARN of the CloudFront function.
	FunctionArn *string `json:"functionArn,omitempty" tf:"function_arn,omitempty"`
}

type DefaultCacheBehaviorFunctionAssociationParameters struct {

	// Specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response.
	// +kubebuilder:validation:Optional
	EventType *string `json:"eventType" tf:"event_type,omitempty"`

	// ARN of the CloudFront function.
	// +kubebuilder:validation:Optional
	FunctionArn *string `json:"functionArn" tf:"function_arn,omitempty"`
}

type DefaultCacheBehaviorLambdaFunctionAssociationInitParameters struct {

	// Specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response.
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// When set to true, the request body is exposed to the Lambda function. Default: false.
	IncludeBody *bool `json:"includeBody,omitempty" tf:"include_body,omitempty"`

	// ARN of the Lambda function.
	LambdaFunctionArn *string `json:"lambdaFunctionArn,omitempty" tf:"lambda_function_arn,omitempty"`
}

type DefaultCacheBehaviorLambdaFunctionAssociationObservation struct {

	// Specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response.
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// When set to true, the request body is exposed to the Lambda function. Default: false.
	IncludeBody *bool `json:"includeBody,omitempty" tf:"include_body,omitempty"`

	// ARN of the Lambda function.
	LambdaFunctionArn *string `json:"lambdaFunctionArn,omitempty" tf:"lambda_function_arn,omitempty"`
}

type DefaultCacheBehaviorLambdaFunctionAssociationParameters struct {

	// Specific event to trigger this function. Valid values: viewer-request, origin-request, viewer-response, origin-response.
	// +kubebuilder:validation:Optional
	EventType *string `json:"eventType" tf:"event_type,omitempty"`

	// When set to true, the request body is exposed to the Lambda function. Default: false.
	// +kubebuilder:validation:Optional
	IncludeBody *bool `json:"includeBody,omitempty" tf:"include_body,omitempty"`

	// ARN of the Lambda function.
	// +kubebuilder:validation:Optional
	LambdaFunctionArn *string `json:"lambdaFunctionArn" tf:"lambda_function_arn,omitempty"`
}

type DefaultCacheBehaviorTrustedKeyGroupsInitParameters struct {

	// Whether the distribution is enabled to accept end user requests for content.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`
}

type DefaultCacheBehaviorTrustedKeyGroupsObservation struct {

	// Whether the distribution is enabled to accept end user requests for content.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`
}

type DefaultCacheBehaviorTrustedKeyGroupsParameters struct {

	// Whether the distribution is enabled to accept end user requests for content.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	// +kubebuilder:validation:Optional
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`
}

type DefinitionInitParameters struct {

	// String schema configuration. See String Schema below.
	StringSchema []StringSchemaInitParameters `json:"stringSchema,omitempty" tf:"string_schema,omitempty"`
}

type DefinitionObservation struct {

	// String schema configuration. See String Schema below.
	StringSchema []StringSchemaObservation `json:"stringSchema,omitempty" tf:"string_schema,omitempty"`
}

type DefinitionParameters struct {

	// String schema configuration. See String Schema below.
	// +kubebuilder:validation:Optional
	StringSchema []StringSchemaParameters `json:"stringSchema,omitempty" tf:"string_schema,omitempty"`
}

type MultitenantDistributionCustomErrorResponseInitParameters struct {

	// Minimum amount of time that you want CloudFront to cache the HTTP status code specified in ErrorCode.
	ErrorCachingMinTTL *float64 `json:"errorCachingMinTtl,omitempty" tf:"error_caching_min_ttl,omitempty"`

	// HTTP status code for which you want to specify a custom error page and/or a caching duration.
	ErrorCode *float64 `json:"errorCode,omitempty" tf:"error_code,omitempty"`

	// HTTP status code that you want CloudFront to return to the viewer along with the custom error page. Both response_code and response_page_path must be specified or both must be omitted.
	ResponseCode *string `json:"responseCode,omitempty" tf:"response_code,omitempty"`

	// Path to the custom error page that you want CloudFront to return to a viewer when your origin returns the HTTP status code specified by ErrorCode. Both response_code and response_page_path must be specified or both must be omitted.
	ResponsePagePath *string `json:"responsePagePath,omitempty" tf:"response_page_path,omitempty"`
}

type MultitenantDistributionCustomErrorResponseObservation struct {

	// Minimum amount of time that you want CloudFront to cache the HTTP status code specified in ErrorCode.
	ErrorCachingMinTTL *float64 `json:"errorCachingMinTtl,omitempty" tf:"error_caching_min_ttl,omitempty"`

	// HTTP status code for which you want to specify a custom error page and/or a caching duration.
	ErrorCode *float64 `json:"errorCode,omitempty" tf:"error_code,omitempty"`

	// HTTP status code that you want CloudFront to return to the viewer along with the custom error page. Both response_code and response_page_path must be specified or both must be omitted.
	ResponseCode *string `json:"responseCode,omitempty" tf:"response_code,omitempty"`

	// Path to the custom error page that you want CloudFront to return to a viewer when your origin returns the HTTP status code specified by ErrorCode. Both response_code and response_page_path must be specified or both must be omitted.
	ResponsePagePath *string `json:"responsePagePath,omitempty" tf:"response_page_path,omitempty"`
}

type MultitenantDistributionCustomErrorResponseParameters struct {

	// Minimum amount of time that you want CloudFront to cache the HTTP status code specified in ErrorCode.
	// +kubebuilder:validation:Optional
	ErrorCachingMinTTL *float64 `json:"errorCachingMinTtl,omitempty" tf:"error_caching_min_ttl,omitempty"`

	// HTTP status code for which you want to specify a custom error page and/or a caching duration.
	// +kubebuilder:validation:Optional
	ErrorCode *float64 `json:"errorCode" tf:"error_code,omitempty"`

	// HTTP status code that you want CloudFront to return to the viewer along with the custom error page. Both response_code and response_page_path must be specified or both must be omitted.
	// +kubebuilder:validation:Optional
	ResponseCode *string `json:"responseCode,omitempty" tf:"response_code,omitempty"`

	// Path to the custom error page that you want CloudFront to return to a viewer when your origin returns the HTTP status code specified by ErrorCode. Both response_code and response_page_path must be specified or both must be omitted.
	// +kubebuilder:validation:Optional
	ResponsePagePath *string `json:"responsePagePath,omitempty" tf:"response_page_path,omitempty"`
}

type MultitenantDistributionDefaultCacheBehaviorInitParameters struct {

	// Controls which HTTP methods CloudFront processes and forwards to your Amazon S3 bucket or your custom origin.
	AllowedMethods []DefaultCacheBehaviorAllowedMethodsInitParameters `json:"allowedMethods,omitempty" tf:"allowed_methods,omitempty"`

	// Unique identifier of the cache policy that is attached to the cache behavior.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/cloudfront/v1beta2.CachePolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	CachePolicyID *string `json:"cachePolicyId,omitempty" tf:"cache_policy_id,omitempty"`

	// Reference to a CachePolicy in cloudfront to populate cachePolicyId.
	// +kubebuilder:validation:Optional
	CachePolicyIDRef *v1.Reference `json:"cachePolicyIdRef,omitempty" tf:"-"`

	// Selector for a CachePolicy in cloudfront to populate cachePolicyId.
	// +kubebuilder:validation:Optional
	CachePolicyIDSelector *v1.Selector `json:"cachePolicyIdSelector,omitempty" tf:"-"`

	// Whether you want CloudFront to automatically compress content for web requests that include Accept-Encoding: gzip in the request header. Default: false.
	Compress *bool `json:"compress,omitempty" tf:"compress,omitempty"`

	// Field level encryption configuration ID.
	FieldLevelEncryptionID *string `json:"fieldLevelEncryptionId,omitempty" tf:"field_level_encryption_id,omitempty"`

	// Configuration block for CloudFront Functions associations. See Function Association below.
	FunctionAssociation []DefaultCacheBehaviorFunctionAssociationInitParameters `json:"functionAssociation,omitempty" tf:"function_association,omitempty"`

	// Configuration block for Lambda@Edge associations. See Lambda Function Association below.
	LambdaFunctionAssociation []DefaultCacheBehaviorLambdaFunctionAssociationInitParameters `json:"lambdaFunctionAssociation,omitempty" tf:"lambda_function_association,omitempty"`

	// Unique identifier of the origin request policy that is attached to the behavior.
	OriginRequestPolicyID *string `json:"originRequestPolicyId,omitempty" tf:"origin_request_policy_id,omitempty"`

	// ARN of the real-time log configuration that is attached to this cache behavior.
	RealtimeLogConfigArn *string `json:"realtimeLogConfigArn,omitempty" tf:"realtime_log_config_arn,omitempty"`

	// Identifier for a response headers policy.
	ResponseHeadersPolicyID *string `json:"responseHeadersPolicyId,omitempty" tf:"response_headers_policy_id,omitempty"`

	// Value of ID for the origin that you want CloudFront to route requests to when a request matches the path pattern either for a cache behavior or for the default cache behavior.
	TargetOriginID *string `json:"targetOriginId,omitempty" tf:"target_origin_id,omitempty"`

	// List of key group IDs that CloudFront can use to validate signed URLs or signed cookies.
	TrustedKeyGroups []DefaultCacheBehaviorTrustedKeyGroupsInitParameters `json:"trustedKeyGroups,omitempty" tf:"trusted_key_groups,omitempty"`

	// Use this element to specify the protocol that users can use to access the files in the origin specified by TargetOriginId when a request matches the path pattern in PathPattern. One of allow-all, https-only, or redirect-to-https.
	ViewerProtocolPolicy *string `json:"viewerProtocolPolicy,omitempty" tf:"viewer_protocol_policy,omitempty"`
}

type MultitenantDistributionDefaultCacheBehaviorObservation struct {

	// Controls which HTTP methods CloudFront processes and forwards to your Amazon S3 bucket or your custom origin.
	AllowedMethods []DefaultCacheBehaviorAllowedMethodsObservation `json:"allowedMethods,omitempty" tf:"allowed_methods,omitempty"`

	// Unique identifier of the cache policy that is attached to the cache behavior.
	CachePolicyID *string `json:"cachePolicyId,omitempty" tf:"cache_policy_id,omitempty"`

	// Whether you want CloudFront to automatically compress content for web requests that include Accept-Encoding: gzip in the request header. Default: false.
	Compress *bool `json:"compress,omitempty" tf:"compress,omitempty"`

	// Field level encryption configuration ID.
	FieldLevelEncryptionID *string `json:"fieldLevelEncryptionId,omitempty" tf:"field_level_encryption_id,omitempty"`

	// Configuration block for CloudFront Functions associations. See Function Association below.
	FunctionAssociation []DefaultCacheBehaviorFunctionAssociationObservation `json:"functionAssociation,omitempty" tf:"function_association,omitempty"`

	// Configuration block for Lambda@Edge associations. See Lambda Function Association below.
	LambdaFunctionAssociation []DefaultCacheBehaviorLambdaFunctionAssociationObservation `json:"lambdaFunctionAssociation,omitempty" tf:"lambda_function_association,omitempty"`

	// Unique identifier of the origin request policy that is attached to the behavior.
	OriginRequestPolicyID *string `json:"originRequestPolicyId,omitempty" tf:"origin_request_policy_id,omitempty"`

	// ARN of the real-time log configuration that is attached to this cache behavior.
	RealtimeLogConfigArn *string `json:"realtimeLogConfigArn,omitempty" tf:"realtime_log_config_arn,omitempty"`

	// Identifier for a response headers policy.
	ResponseHeadersPolicyID *string `json:"responseHeadersPolicyId,omitempty" tf:"response_headers_policy_id,omitempty"`

	// Value of ID for the origin that you want CloudFront to route requests to when a request matches the path pattern either for a cache behavior or for the default cache behavior.
	TargetOriginID *string `json:"targetOriginId,omitempty" tf:"target_origin_id,omitempty"`

	// List of key group IDs that CloudFront can use to validate signed URLs or signed cookies.
	TrustedKeyGroups []DefaultCacheBehaviorTrustedKeyGroupsObservation `json:"trustedKeyGroups,omitempty" tf:"trusted_key_groups,omitempty"`

	// Use this element to specify the protocol that users can use to access the files in the origin specified by TargetOriginId when a request matches the path pattern in PathPattern. One of allow-all, https-only, or redirect-to-https.
	ViewerProtocolPolicy *string `json:"viewerProtocolPolicy,omitempty" tf:"viewer_protocol_policy,omitempty"`
}

type MultitenantDistributionDefaultCacheBehaviorParameters struct {

	// Controls which HTTP methods CloudFront processes and forwards to your Amazon S3 bucket or your custom origin.
	// +kubebuilder:validation:Optional
	AllowedMethods []DefaultCacheBehaviorAllowedMethodsParameters `json:"allowedMethods,omitempty" tf:"allowed_methods,omitempty"`

	// Unique identifier of the cache policy that is attached to the cache behavior.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/cloudfront/v1beta2.CachePolicy
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	CachePolicyID *string `json:"cachePolicyId,omitempty" tf:"cache_policy_id,omitempty"`

	// Reference to a CachePolicy in cloudfront to populate cachePolicyId.
	// +kubebuilder:validation:Optional
	CachePolicyIDRef *v1.Reference `json:"cachePolicyIdRef,omitempty" tf:"-"`

	// Selector for a CachePolicy in cloudfront to populate cachePolicyId.
	// +kubebuilder:validation:Optional
	CachePolicyIDSelector *v1.Selector `json:"cachePolicyIdSelector,omitempty" tf:"-"`

	// Whether you want CloudFront to automatically compress content for web requests that include Accept-Encoding: gzip in the request header. Default: false.
	// +kubebuilder:validation:Optional
	Compress *bool `json:"compress,omitempty" tf:"compress,omitempty"`

	// Field level encryption configuration ID.
	// +kubebuilder:validation:Optional
	FieldLevelEncryptionID *string `json:"fieldLevelEncryptionId,omitempty" tf:"field_level_encryption_id,omitempty"`

	// Configuration block for CloudFront Functions associations. See Function Association below.
	// +kubebuilder:validation:Optional
	FunctionAssociation []DefaultCacheBehaviorFunctionAssociationParameters `json:"functionAssociation,omitempty" tf:"function_association,omitempty"`

	// Configuration block for Lambda@Edge associations. See Lambda Function Association below.
	// +kubebuilder:validation:Optional
	LambdaFunctionAssociation []DefaultCacheBehaviorLambdaFunctionAssociationParameters `json:"lambdaFunctionAssociation,omitempty" tf:"lambda_function_association,omitempty"`

	// Unique identifier of the origin request policy that is attached to the behavior.
	// +kubebuilder:validation:Optional
	OriginRequestPolicyID *string `json:"originRequestPolicyId,omitempty" tf:"origin_request_policy_id,omitempty"`

	// ARN of the real-time log configuration that is attached to this cache behavior.
	// +kubebuilder:validation:Optional
	RealtimeLogConfigArn *string `json:"realtimeLogConfigArn,omitempty" tf:"realtime_log_config_arn,omitempty"`

	// Identifier for a response headers policy.
	// +kubebuilder:validation:Optional
	ResponseHeadersPolicyID *string `json:"responseHeadersPolicyId,omitempty" tf:"response_headers_policy_id,omitempty"`

	// Value of ID for the origin that you want CloudFront to route requests to when a request matches the path pattern either for a cache behavior or for the default cache behavior.
	// +kubebuilder:validation:Optional
	TargetOriginID *string `json:"targetOriginId" tf:"target_origin_id,omitempty"`

	// List of key group IDs that CloudFront can use to validate signed URLs or signed cookies.
	// +kubebuilder:validation:Optional
	TrustedKeyGroups []DefaultCacheBehaviorTrustedKeyGroupsParameters `json:"trustedKeyGroups,omitempty" tf:"trusted_key_groups,omitempty"`

	// Use this element to specify the protocol that users can use to access the files in the origin specified by TargetOriginId when a request matches the path pattern in PathPattern. One of allow-all, https-only, or redirect-to-https.
	// +kubebuilder:validation:Optional
	ViewerProtocolPolicy *string `json:"viewerProtocolPolicy" tf:"viewer_protocol_policy,omitempty"`
}

type MultitenantDistributionInitParameters struct {

	// List of key groups that CloudFront can use to validate signed URLs or signed cookies. See Active Trusted Key Groups below.
	ActiveTrustedKeyGroups []ActiveTrustedKeyGroupsInitParameters `json:"activeTrustedKeyGroups,omitempty" tf:"active_trusted_key_groups,omitempty"`

	// Ordered list of cache behaviors resource for this distribution. See Cache Behavior below.
	CacheBehavior []CacheBehaviorInitParameters `json:"cacheBehavior,omitempty" tf:"cache_behavior,omitempty"`

	// Any comments you want to include about the distribution.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// One or more custom error response elements. See Custom Error Response below.
	CustomErrorResponse []MultitenantDistributionCustomErrorResponseInitParameters `json:"customErrorResponse,omitempty" tf:"custom_error_response,omitempty"`

	// Default cache behavior for this distribution. See Default Cache Behavior below.
	DefaultCacheBehavior []MultitenantDistributionDefaultCacheBehaviorInitParameters `json:"defaultCacheBehavior,omitempty" tf:"default_cache_behavior,omitempty"`

	// Object that you want CloudFront to return when an end user requests the root URL.
	DefaultRootObject *string `json:"defaultRootObject,omitempty" tf:"default_root_object,omitempty"`

	// Whether the distribution is enabled to accept end user requests for content.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Maximum HTTP version to support on the distribution. Allowed values are http1.1, http2, http2and3, and http3. Default: http2.
	HTTPVersion *string `json:"httpVersion,omitempty" tf:"http_version,omitempty"`

	// One or more origins for this distribution (multiples allowed). See Origin below.
	Origin []MultitenantDistributionOriginInitParameters `json:"origin,omitempty" tf:"origin,omitempty"`

	// One or more origin_group for this distribution (multiples allowed). See Origin Group below.
	OriginGroup []MultitenantDistributionOriginGroupInitParameters `json:"originGroup,omitempty" tf:"origin_group,omitempty"`

	// Restriction configuration for this distribution. See Restrictions below.
	Restrictions []MultitenantDistributionRestrictionsInitParameters `json:"restrictions,omitempty" tf:"restrictions,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Tenant configuration that contains parameter definitions for multi-tenant distributions. See Tenant Config below.
	TenantConfig []TenantConfigInitParameters `json:"tenantConfig,omitempty" tf:"tenant_config,omitempty"`

	// SSL configuration for this distribution. See Viewer Certificate below.
	ViewerCertificate []MultitenantDistributionViewerCertificateInitParameters `json:"viewerCertificate,omitempty" tf:"viewer_certificate,omitempty"`

	// Unique identifier that specifies the AWS WAF v2 web ACL to associate with this distribution.
	WebACLID *string `json:"webAclId,omitempty" tf:"web_acl_id,omitempty"`
}

type MultitenantDistributionObservation struct {

	// List of key groups that CloudFront can use to validate signed URLs or signed cookies. See Active Trusted Key Groups below.
	ActiveTrustedKeyGroups []ActiveTrustedKeyGroupsObservation `json:"activeTrustedKeyGroups,omitempty" tf:"active_trusted_key_groups,omitempty"`

	// ARN for the distribution.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// Ordered list of cache behaviors resource for this distribution. See Cache Behavior below.
	CacheBehavior []CacheBehaviorObservation `json:"cacheBehavior,omitempty" tf:"cache_behavior,omitempty"`

	// Internal value used by CloudFront to allow future updates to the distribution configuration.
	CallerReference *string `json:"callerReference,omitempty" tf:"caller_reference,omitempty"`

	// Any comments you want to include about the distribution.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Connection mode for the distribution. Always set to tenant-only for multi-tenant distributions.
	ConnectionMode *string `json:"connectionMode,omitempty" tf:"connection_mode,omitempty"`

	// One or more custom error response elements. See Custom Error Response below.
	CustomErrorResponse []MultitenantDistributionCustomErrorResponseObservation `json:"customErrorResponse,omitempty" tf:"custom_error_response,omitempty"`

	// Default cache behavior for this distribution. See Default Cache Behavior below.
	DefaultCacheBehavior []MultitenantDistributionDefaultCacheBehaviorObservation `json:"defaultCacheBehavior,omitempty" tf:"default_cache_behavior,omitempty"`

	// Object that you want CloudFront to return when an end user requests the root URL.
	DefaultRootObject *string `json:"defaultRootObject,omitempty" tf:"default_root_object,omitempty"`

	// DNS domain name of either the S3 bucket, or web site of your custom origin.
	DomainName *string `json:"domainName,omitempty" tf:"domain_name,omitempty"`

	// Whether the distribution is enabled to accept end user requests for content.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Current version of the distribution's information.
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	// Maximum HTTP version to support on the distribution. Allowed values are http1.1, http2, http2and3, and http3. Default: http2.
	HTTPVersion *string `json:"httpVersion,omitempty" tf:"http_version,omitempty"`

	// Identifier for the distribution.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Number of invalidation batches currently in progress.
	InProgressInvalidationBatches *float64 `json:"inProgressInvalidationBatches,omitempty" tf:"in_progress_invalidation_batches,omitempty"`

	// Date and time the distribution was last modified.
	LastModifiedTime *string `json:"lastModifiedTime,omitempty" tf:"last_modified_time,omitempty"`

	// One or more origins for this distribution (multiples allowed). See Origin below.
	Origin []MultitenantDistributionOriginObservation `json:"origin,omitempty" tf:"origin,omitempty"`

	// One or more origin_group for this distribution (multiples allowed). See Origin Group below.
	OriginGroup []MultitenantDistributionOriginGroupObservation `json:"originGroup,omitempty" tf:"origin_group,omitempty"`

	// Restriction configuration for this distribution. See Restrictions below.
	Restrictions []MultitenantDistributionRestrictionsObservation `json:"restrictions,omitempty" tf:"restrictions,omitempty"`

	// Current status of the distribution. Deployed if the distribution's information is fully propagated throughout the Amazon CloudFront system.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	// +mapType=granular
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`

	// Tenant configuration that contains parameter definitions for multi-tenant distributions. See Tenant Config below.
	TenantConfig []TenantConfigObservation `json:"tenantConfig,omitempty" tf:"tenant_config,omitempty"`

	// SSL configuration for this distribution. See Viewer Certificate below.
	ViewerCertificate []MultitenantDistributionViewerCertificateObservation `json:"viewerCertificate,omitempty" tf:"viewer_certificate,omitempty"`

	// Unique identifier that specifies the AWS WAF v2 web ACL to associate with this distribution.
	WebACLID *string `json:"webAclId,omitempty" tf:"web_acl_id,omitempty"`
}

type MultitenantDistributionOriginGroupInitParameters struct {

	// Failover criteria for when to failover to the secondary origin. See Failover Criteria below.
	FailoverCriteria []OriginGroupFailoverCriteriaInitParameters `json:"failoverCriteria,omitempty" tf:"failover_criteria,omitempty"`

	// Identifier for the distribution.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of origins in this origin group. Must contain exactly 2 members. See Origin Group Member below.
	Member []OriginGroupMemberInitParameters `json:"member,omitempty" tf:"member,omitempty"`
}

type MultitenantDistributionOriginGroupObservation struct {

	// Failover criteria for when to failover to the secondary origin. See Failover Criteria below.
	FailoverCriteria []OriginGroupFailoverCriteriaObservation `json:"failoverCriteria,omitempty" tf:"failover_criteria,omitempty"`

	// Identifier for the distribution.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of origins in this origin group. Must contain exactly 2 members. See Origin Group Member below.
	Member []OriginGroupMemberObservation `json:"member,omitempty" tf:"member,omitempty"`
}

type MultitenantDistributionOriginGroupParameters struct {

	// Failover criteria for when to failover to the secondary origin. See Failover Criteria below.
	// +kubebuilder:validation:Optional
	FailoverCriteria []OriginGroupFailoverCriteriaParameters `json:"failoverCriteria,omitempty" tf:"failover_criteria,omitempty"`

	// Identifier for the distribution.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// List of origins in this origin group. Must contain exactly 2 members. See Origin Group Member below.
	// +kubebuilder:validation:Optional
	Member []OriginGroupMemberParameters `json:"member,omitempty" tf:"member,omitempty"`
}

type MultitenantDistributionOriginInitParameters struct {

	// Number of times that CloudFront attempts to connect to the origin. Must be between 1-3. Default: 3.
	ConnectionAttempts *float64 `json:"connectionAttempts,omitempty" tf:"connection_attempts,omitempty"`

	// Number of seconds that CloudFront waits when trying to establish a connection to the origin. Must be between 1-10. Default: 10.
	ConnectionTimeout *float64 `json:"connectionTimeout,omitempty" tf:"connection_timeout,omitempty"`

	// One or more sub-resources with name and value parameters that specify header data that will be sent to the origin. See Custom Header below.
	CustomHeader []OriginCustomHeaderInitParameters `json:"customHeader,omitempty" tf:"custom_header,omitempty"`

	// CloudFront origin access identity to associate with the origin. See Custom Origin Config below.
	CustomOriginConfig []OriginCustomOriginConfigInitParameters `json:"customOriginConfig,omitempty" tf:"custom_origin_config,omitempty"`

	// DNS domain name of either the S3 bucket, or web site of your custom origin.
	DomainName *string `json:"domainName,omitempty" tf:"domain_name,omitempty"`

	// Identifier for the distribution.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// CloudFront origin access control identifier to associate with the origin.
	OriginAccessControlID *string `json:"originAccessControlId,omitempty" tf:"origin_access_control_id,omitempty"`

	// Optional element that causes CloudFront to request your content from a directory in your Amazon S3 bucket or your custom origin.
	OriginPath *string `json:"originPath,omitempty" tf:"origin_path,omitempty"`

	// CloudFront Origin Shield configuration information. See Origin Shield below.
	OriginShield []OriginOriginShieldInitParameters `json:"originShield,omitempty" tf:"origin_shield,omitempty"`

	// Number of seconds that CloudFront waits for a response after forwarding a request to the origin. Default: 30.
	ResponseCompletionTimeout *float64 `json:"responseCompletionTimeout,omitempty" tf:"response_completion_timeout,omitempty"`

	// CloudFront VPC origin configuration. See VPC Origin Config below.
	VPCOriginConfig []OriginVPCOriginConfigInitParameters `json:"vpcOriginConfig,omitempty" tf:"vpc_origin_config,omitempty"`
}

type MultitenantDistributionOriginObservation struct {

	// Number of times that CloudFront attempts to connect to the origin. Must be between 1-3. Default: 3.
	ConnectionAttempts *float64 `json:"connectionAttempts,omitempty" tf:"connection_attempts,omitempty"`

	// Number of seconds that CloudFront waits when trying to establish a connection to the origin. Must be between 1-10. Default: 10.
	ConnectionTimeout *float64 `json:"connectionTimeout,omitempty" tf:"connection_timeout,omitempty"`

	// One or more sub-resources with name and value parameters that specify header data that will be sent to the origin. See Custom Header below.
	CustomHeader []OriginCustomHeaderObservation `json:"customHeader,omitempty" tf:"custom_header,omitempty"`

	// CloudFront origin access identity to associate with the origin. See Custom Origin Config below.
	CustomOriginConfig []OriginCustomOriginConfigObservation `json:"customOriginConfig,omitempty" tf:"custom_origin_config,omitempty"`

	// DNS domain name of either the S3 bucket, or web site of your custom origin.
	DomainName *string `json:"domainName,omitempty" tf:"domain_name,omitempty"`

	// Identifier for the distribution.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// CloudFront origin access control identifier to associate with the origin.
	OriginAccessControlID *string `json:"originAccessControlId,omitempty" tf:"origin_access_control_id,omitempty"`

	// Optional element that causes CloudFront to request your content from a directory in your Amazon S3 bucket or your custom origin.
	OriginPath *string `json:"originPath,omitempty" tf:"origin_path,omitempty"`

	// CloudFront Origin Shield configuration information. See Origin Shield below.
	OriginShield []OriginOriginShieldObservation `json:"originShield,omitempty" tf:"origin_shield,omitempty"`

	// Number of seconds that CloudFront waits for a response after forwarding a request to the origin. Default: 30.
	ResponseCompletionTimeout *float64 `json:"responseCompletionTimeout,omitempty" tf:"response_completion_timeout,omitempty"`

	// CloudFront VPC origin configuration. See VPC Origin Config below.
	VPCOriginConfig []OriginVPCOriginConfigObservation `json:"vpcOriginConfig,omitempty" tf:"vpc_origin_config,omitempty"`
}

type MultitenantDistributionOriginParameters struct {

	// Number of times that CloudFront attempts to connect to the origin. Must be between 1-3. Default: 3.
	// +kubebuilder:validation:Optional
	ConnectionAttempts *float64 `json:"connectionAttempts,omitempty" tf:"connection_attempts,omitempty"`

	// Number of seconds that CloudFront waits when trying to establish a connection to the origin. Must be between 1-10. Default: 10.
	// +kubebuilder:validation:Optional
	ConnectionTimeout *float64 `json:"connectionTimeout,omitempty" tf:"connection_timeout,omitempty"`

	// One or more sub-resources with name and value parameters that specify header data that will be sent to the origin. See Custom Header below.
	// +kubebuilder:validation:Optional
	CustomHeader []OriginCustomHeaderParameters `json:"customHeader,omitempty" tf:"custom_header,omitempty"`

	// CloudFront origin access identity to associate with the origin. See Custom Origin Config below.
	// +kubebuilder:validation:Optional
	CustomOriginConfig []OriginCustomOriginConfigParameters `json:"customOriginConfig,omitempty" tf:"custom_origin_config,omitempty"`

	// DNS domain name of either the S3 bucket, or web site of your custom origin.
	// +kubebuilder:validation:Optional
	DomainName *string `json:"domainName" tf:"domain_name,omitempty"`

	// Identifier for the distribution.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// CloudFront origin access control identifier to associate with the origin.
	// +kubebuilder:validation:Optional
	OriginAccessControlID *string `json:"originAccessControlId,omitempty" tf:"origin_access_control_id,omitempty"`

	// Optional element that causes CloudFront to request your content from a directory in your Amazon S3 bucket or your custom origin.
	// +kubebuilder:validation:Optional
	OriginPath *string `json:"originPath,omitempty" tf:"origin_path,omitempty"`

	// CloudFront Origin Shield configuration information. See Origin Shield below.
	// +kubebuilder:validation:Optional
	OriginShield []OriginOriginShieldParameters `json:"originShield,omitempty" tf:"origin_shield,omitempty"`

	// Number of seconds that CloudFront waits for a response after forwarding a request to the origin. Default: 30.
	// +kubebuilder:validation:Optional
	ResponseCompletionTimeout *float64 `json:"responseCompletionTimeout,omitempty" tf:"response_completion_timeout,omitempty"`

	// CloudFront VPC origin configuration. See VPC Origin Config below.
	// +kubebuilder:validation:Optional
	VPCOriginConfig []OriginVPCOriginConfigParameters `json:"vpcOriginConfig,omitempty" tf:"vpc_origin_config,omitempty"`
}

type MultitenantDistributionParameters struct {

	// List of key groups that CloudFront can use to validate signed URLs or signed cookies. See Active Trusted Key Groups below.
	// +kubebuilder:validation:Optional
	ActiveTrustedKeyGroups []ActiveTrustedKeyGroupsParameters `json:"activeTrustedKeyGroups,omitempty" tf:"active_trusted_key_groups,omitempty"`

	// Ordered list of cache behaviors resource for this distribution. See Cache Behavior below.
	// +kubebuilder:validation:Optional
	CacheBehavior []CacheBehaviorParameters `json:"cacheBehavior,omitempty" tf:"cache_behavior,omitempty"`

	// Any comments you want to include about the distribution.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// One or more custom error response elements. See Custom Error Response below.
	// +kubebuilder:validation:Optional
	CustomErrorResponse []MultitenantDistributionCustomErrorResponseParameters `json:"customErrorResponse,omitempty" tf:"custom_error_response,omitempty"`

	// Default cache behavior for this distribution. See Default Cache Behavior below.
	// +kubebuilder:validation:Optional
	DefaultCacheBehavior []MultitenantDistributionDefaultCacheBehaviorParameters `json:"defaultCacheBehavior,omitempty" tf:"default_cache_behavior,omitempty"`

	// Object that you want CloudFront to return when an end user requests the root URL.
	// +kubebuilder:validation:Optional
	DefaultRootObject *string `json:"defaultRootObject,omitempty" tf:"default_root_object,omitempty"`

	// Whether the distribution is enabled to accept end user requests for content.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Maximum HTTP version to support on the distribution. Allowed values are http1.1, http2, http2and3, and http3. Default: http2.
	// +kubebuilder:validation:Optional
	HTTPVersion *string `json:"httpVersion,omitempty" tf:"http_version,omitempty"`

	// One or more origins for this distribution (multiples allowed). See Origin below.
	// +kubebuilder:validation:Optional
	Origin []MultitenantDistributionOriginParameters `json:"origin,omitempty" tf:"origin,omitempty"`

	// One or more origin_group for this distribution (multiples allowed). See Origin Group below.
	// +kubebuilder:validation:Optional
	OriginGroup []MultitenantDistributionOriginGroupParameters `json:"originGroup,omitempty" tf:"origin_group,omitempty"`

	// Restriction configuration for this distribution. See Restrictions below.
	// +kubebuilder:validation:Optional
	Restrictions []MultitenantDistributionRestrictionsParameters `json:"restrictions,omitempty" tf:"restrictions,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Tenant configuration that contains parameter definitions for multi-tenant distributions. See Tenant Config below.
	// +kubebuilder:validation:Optional
	TenantConfig []TenantConfigParameters `json:"tenantConfig,omitempty" tf:"tenant_config,omitempty"`

	// SSL configuration for this distribution. See Viewer Certificate below.
	// +kubebuilder:validation:Optional
	ViewerCertificate []MultitenantDistributionViewerCertificateParameters `json:"viewerCertificate,omitempty" tf:"viewer_certificate,omitempty"`

	// Unique identifier that specifies the AWS WAF v2 web ACL to associate with this distribution.
	// +kubebuilder:validation:Optional
	WebACLID *string `json:"webAclId,omitempty" tf:"web_acl_id,omitempty"`
}

type MultitenantDistributionRestrictionsInitParameters struct {

	// Geographic restriction configuration. See Geo Restriction below.
	GeoRestriction []RestrictionsGeoRestrictionInitParameters `json:"geoRestriction,omitempty" tf:"geo_restriction,omitempty"`
}

type MultitenantDistributionRestrictionsObservation struct {

	// Geographic restriction configuration. See Geo Restriction below.
	GeoRestriction []RestrictionsGeoRestrictionObservation `json:"geoRestriction,omitempty" tf:"geo_restriction,omitempty"`
}

type MultitenantDistributionRestrictionsParameters struct {

	// Geographic restriction configuration. See Geo Restriction below.
	// +kubebuilder:validation:Optional
	GeoRestriction []RestrictionsGeoRestrictionParameters `json:"geoRestriction,omitempty" tf:"geo_restriction,omitempty"`
}

type MultitenantDistributionViewerCertificateInitParameters struct {

	// ARN of the AWS Certificate Manager certificate that you wish to use with this distribution. Required when using a custom SSL certificate.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/acm/v1beta2.Certificate
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("arn",true)
	AcmCertificateArn *string `json:"acmCertificateArn,omitempty" tf:"acm_certificate_arn,omitempty"`

	// Reference to a Certificate in acm to populate acmCertificateArn.
	// +kubebuilder:validation:Optional
	AcmCertificateArnRef *v1.Reference `json:"acmCertificateArnRef,omitempty" tf:"-"`

	// Selector for a Certificate in acm to populate acmCertificateArn.
	// +kubebuilder:validation:Optional
	AcmCertificateArnSelector *v1.Selector `json:"acmCertificateArnSelector,omitempty" tf:"-"`

	// Whether to use the CloudFront default certificate. Cannot be used with acm_certificate_arn.
	CloudfrontDefaultCertificate *bool `json:"cloudfrontDefaultCertificate,omitempty" tf:"cloudfront_default_certificate,omitempty"`

	// Minimum version of the SSL protocol that you want CloudFront to use for HTTPS connections. Default: TLSv1.
	MinimumProtocolVersion *string `json:"minimumProtocolVersion,omitempty" tf:"minimum_protocol_version,omitempty"`

	// How you want CloudFront to serve HTTPS requests. Valid values are sni-only and vip. Required when acm_certificate_arn is specified.
	SSLSupportMethod *string `json:"sslSupportMethod,omitempty" tf:"ssl_support_method,omitempty"`
}

type MultitenantDistributionViewerCertificateObservation struct {

	// ARN of the AWS Certificate Manager certificate that you wish to use with this distribution. Required when using a custom SSL certificate.
	AcmCertificateArn *string `json:"acmCertificateArn,omitempty" tf:"acm_certificate_arn,omitempty"`

	// Whether to use the CloudFront default certificate. Cannot be used with acm_certificate_arn.
	CloudfrontDefaultCertificate *bool `json:"cloudfrontDefaultCertificate,omitempty" tf:"cloudfront_default_certificate,omitempty"`

	// Minimum version of the SSL protocol that you want CloudFront to use for HTTPS connections. Default: TLSv1.
	MinimumProtocolVersion *string `json:"minimumProtocolVersion,omitempty" tf:"minimum_protocol_version,omitempty"`

	// How you want CloudFront to serve HTTPS requests. Valid values are sni-only and vip. Required when acm_certificate_arn is specified.
	SSLSupportMethod *string `json:"sslSupportMethod,omitempty" tf:"ssl_support_method,omitempty"`
}

type MultitenantDistributionViewerCertificateParameters struct {

	// ARN of the AWS Certificate Manager certificate that you wish to use with this distribution. Required when using a custom SSL certificate.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/acm/v1beta2.Certificate
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("arn",true)
	// +kubebuilder:validation:Optional
	AcmCertificateArn *string `json:"acmCertificateArn,omitempty" tf:"acm_certificate_arn,omitempty"`

	// Reference to a Certificate in acm to populate acmCertificateArn.
	// +kubebuilder:validation:Optional
	AcmCertificateArnRef *v1.Reference `json:"acmCertificateArnRef,omitempty" tf:"-"`

	// Selector for a Certificate in acm to populate acmCertificateArn.
	// +kubebuilder:validation:Optional
	AcmCertificateArnSelector *v1.Selector `json:"acmCertificateArnSelector,omitempty" tf:"-"`

	// Whether to use the CloudFront default certificate. Cannot be used with acm_certificate_arn.
	// +kubebuilder:validation:Optional
	CloudfrontDefaultCertificate *bool `json:"cloudfrontDefaultCertificate,omitempty" tf:"cloudfront_default_certificate,omitempty"`

	// Minimum version of the SSL protocol that you want CloudFront to use for HTTPS connections. Default: TLSv1.
	// +kubebuilder:validation:Optional
	MinimumProtocolVersion *string `json:"minimumProtocolVersion,omitempty" tf:"minimum_protocol_version,omitempty"`

	// How you want CloudFront to serve HTTPS requests. Valid values are sni-only and vip. Required when acm_certificate_arn is specified.
	// +kubebuilder:validation:Optional
	SSLSupportMethod *string `json:"sslSupportMethod,omitempty" tf:"ssl_support_method,omitempty"`
}

type OriginCustomHeaderInitParameters struct {

	// Name of the header.
	HeaderName *string `json:"headerName,omitempty" tf:"header_name,omitempty"`

	// Value for the header.
	HeaderValue *string `json:"headerValue,omitempty" tf:"header_value,omitempty"`
}

type OriginCustomHeaderObservation struct {

	// Name of the header.
	HeaderName *string `json:"headerName,omitempty" tf:"header_name,omitempty"`

	// Value for the header.
	HeaderValue *string `json:"headerValue,omitempty" tf:"header_value,omitempty"`
}

type OriginCustomHeaderParameters struct {

	// Name of the header.
	// +kubebuilder:validation:Optional
	HeaderName *string `json:"headerName" tf:"header_name,omitempty"`

	// Value for the header.
	// +kubebuilder:validation:Optional
	HeaderValue *string `json:"headerValue" tf:"header_value,omitempty"`
}

type OriginCustomOriginConfigInitParameters struct {

	// HTTP port the custom origin listens on.
	HTTPPort *float64 `json:"httpPort,omitempty" tf:"http_port,omitempty"`

	// HTTPS port the custom origin listens on.
	HTTPSPort *float64 `json:"httpsPort,omitempty" tf:"https_port,omitempty"`

	// Type of IP addresses used by your origins. Valid values are ipv4 and dualstack.
	IPAddressType *string `json:"ipAddressType,omitempty" tf:"ip_address_type,omitempty"`

	// Custom keep-alive timeout, in seconds. Default: 5.
	OriginKeepaliveTimeout *float64 `json:"originKeepaliveTimeout,omitempty" tf:"origin_keepalive_timeout,omitempty"`

	// Origin protocol policy to apply to your origin. Valid values are http-only, https-only, and match-viewer.
	OriginProtocolPolicy *string `json:"originProtocolPolicy,omitempty" tf:"origin_protocol_policy,omitempty"`

	// Custom read timeout, in seconds. Default: 30.
	OriginReadTimeout *float64 `json:"originReadTimeout,omitempty" tf:"origin_read_timeout,omitempty"`

	// List of SSL/TLS protocols that you want CloudFront to use when communicating with your origin over HTTPS.
	// +listType=set
	OriginSSLProtocols []*string `json:"originSslProtocols,omitempty" tf:"origin_ssl_protocols,omitempty"`
}

type OriginCustomOriginConfigObservation struct {

	// HTTP port the custom origin listens on.
	HTTPPort *float64 `json:"httpPort,omitempty" tf:"http_port,omitempty"`

	// HTTPS port the custom origin listens on.
	HTTPSPort *float64 `json:"httpsPort,omitempty" tf:"https_port,omitempty"`

	// Type of IP addresses used by your origins. Valid values are ipv4 and dualstack.
	IPAddressType *string `json:"ipAddressType,omitempty" tf:"ip_address_type,omitempty"`

	// Custom keep-alive timeout, in seconds. Default: 5.
	OriginKeepaliveTimeout *float64 `json:"originKeepaliveTimeout,omitempty" tf:"origin_keepalive_timeout,omitempty"`

	// Origin protocol policy to apply to your origin. Valid values are http-only, https-only, and match-viewer.
	OriginProtocolPolicy *string `json:"originProtocolPolicy,omitempty" tf:"origin_protocol_policy,omitempty"`

	// Custom read timeout, in seconds. Default: 30.
	OriginReadTimeout *float64 `json:"originReadTimeout,omitempty" tf:"origin_read_timeout,omitempty"`

	// List of SSL/TLS protocols that you want CloudFront to use when communicating with your origin over HTTPS.
	// +listType=set
	OriginSSLProtocols []*string `json:"originSslProtocols,omitempty" tf:"origin_ssl_protocols,omitempty"`
}

type OriginCustomOriginConfigParameters struct {

	// HTTP port the custom origin listens on.
	// +kubebuilder:validation:Optional
	HTTPPort *float64 `json:"httpPort" tf:"http_port,omitempty"`

	// HTTPS port the custom origin listens on.
	// +kubebuilder:validation:Optional
	HTTPSPort *float64 `json:"httpsPort" tf:"https_port,omitempty"`

	// Type of IP addresses used by your origins. Valid values are ipv4 and dualstack.
	// +kubebuilder:validation:Optional
	IPAddressType *string `json:"ipAddressType,omitempty" tf:"ip_address_type,omitempty"`

	// Custom keep-alive timeout, in seconds. Default: 5.
	// +kubebuilder:validation:Optional
	OriginKeepaliveTimeout *float64 `json:"originKeepaliveTimeout,omitempty" tf:"origin_keepalive_timeout,omitempty"`

	// Origin protocol policy to apply to your origin. Valid values are http-only, https-only, and match-viewer.
	// +kubebuilder:validation:Optional
	OriginProtocolPolicy *string `json:"originProtocolPolicy" tf:"origin_protocol_policy,omitempty"`

	// Custom read timeout, in seconds. Default: 30.
	// +kubebuilder:validation:Optional
	OriginReadTimeout *float64 `json:"originReadTimeout,omitempty" tf:"origin_read_timeout,omitempty"`

	// List of SSL/TLS protocols that you want CloudFront to use when communicating with your origin over HTTPS.
	// +kubebuilder:validation:Optional
	// +listType=set
	OriginSSLProtocols []*string `json:"originSslProtocols" tf:"origin_ssl_protocols,omitempty"`
}

type OriginGroupFailoverCriteriaInitParameters struct {

	// List of HTTP status codes that trigger a failover to the secondary origin.
	// +listType=set
	StatusCodes []*float64 `json:"statusCodes,omitempty" tf:"status_codes,omitempty"`
}

type OriginGroupFailoverCriteriaObservation struct {

	// List of HTTP status codes that trigger a failover to the secondary origin.
	// +listType=set
	StatusCodes []*float64 `json:"statusCodes,omitempty" tf:"status_codes,omitempty"`
}

type OriginGroupFailoverCriteriaParameters struct {

	// List of HTTP status codes that trigger a failover to the secondary origin.
	// +kubebuilder:validation:Optional
	// +listType=set
	StatusCodes []*float64 `json:"statusCodes" tf:"status_codes,omitempty"`
}

type OriginGroupMemberInitParameters struct {

	// Unique identifier for the origin.
	OriginID *string `json:"originId,omitempty" tf:"origin_id,omitempty"`
}

type OriginGroupMemberObservation struct {

	// Unique identifier for the origin.
	OriginID *string `json:"originId,omitempty" tf:"origin_id,omitempty"`
}

type OriginGroupMemberParameters struct {

	// Unique identifier for the origin.
	// +kubebuilder:validation:Optional
	OriginID *string `json:"originId" tf:"origin_id,omitempty"`
}

type OriginOriginShieldInitParameters struct {

	// Whether the distribution is enabled to accept end user requests for content.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// AWS Region for Origin Shield. Required when enabled is true.
	OriginShieldRegion *string `json:"originShieldRegion,omitempty" tf:"origin_shield_region,omitempty"`
}

type OriginOriginShieldObservation struct {

	// Whether the distribution is enabled to accept end user requests for content.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// AWS Region for Origin Shield. Required when enabled is true.
	OriginShieldRegion *string `json:"originShieldRegion,omitempty" tf:"origin_shield_region,omitempty"`
}

type OriginOriginShieldParameters struct {

	// Whether the distribution is enabled to accept end user requests for content.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// AWS Region for Origin Shield. Required when enabled is true.
	// +kubebuilder:validation:Optional
	OriginShieldRegion *string `json:"originShieldRegion,omitempty" tf:"origin_shield_region,omitempty"`
}

type OriginVPCOriginConfigInitParameters struct {

	// Custom keep-alive timeout, in seconds. Default: 5.
	OriginKeepaliveTimeout *float64 `json:"originKeepaliveTimeout,omitempty" tf:"origin_keepalive_timeout,omitempty"`

	// Custom read timeout, in seconds. Default: 30.
	OriginReadTimeout *float64 `json:"originReadTimeout,omitempty" tf:"origin_read_timeout,omitempty"`

	// ID of the VPC origin that you want CloudFront to route requests to.
	VPCOriginID *string `json:"vpcOriginId,omitempty" tf:"vpc_origin_id,omitempty"`
}

type OriginVPCOriginConfigObservation struct {

	// Custom keep-alive timeout, in seconds. Default: 5.
	OriginKeepaliveTimeout *float64 `json:"originKeepaliveTimeout,omitempty" tf:"origin_keepalive_timeout,omitempty"`

	// Custom read timeout, in seconds. Default: 30.
	OriginReadTimeout *float64 `json:"originReadTimeout,omitempty" tf:"origin_read_timeout,omitempty"`

	// ID of the VPC origin that you want CloudFront to route requests to.
	VPCOriginID *string `json:"vpcOriginId,omitempty" tf:"vpc_origin_id,omitempty"`
}

type OriginVPCOriginConfigParameters struct {

	// Custom keep-alive timeout, in seconds. Default: 5.
	// +kubebuilder:validation:Optional
	OriginKeepaliveTimeout *float64 `json:"originKeepaliveTimeout,omitempty" tf:"origin_keepalive_timeout,omitempty"`

	// Custom read timeout, in seconds. Default: 30.
	// +kubebuilder:validation:Optional
	OriginReadTimeout *float64 `json:"originReadTimeout,omitempty" tf:"origin_read_timeout,omitempty"`

	// ID of the VPC origin that you want CloudFront to route requests to.
	// +kubebuilder:validation:Optional
	VPCOriginID *string `json:"vpcOriginId" tf:"vpc_origin_id,omitempty"`
}

type ParameterDefinitionInitParameters struct {

	// Definition of the parameter schema. See Parameter Definition Schema below.
	Definition []DefinitionInitParameters `json:"definition,omitempty" tf:"definition,omitempty"`

	// Name of the parameter.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ParameterDefinitionObservation struct {

	// Definition of the parameter schema. See Parameter Definition Schema below.
	Definition []DefinitionObservation `json:"definition,omitempty" tf:"definition,omitempty"`

	// Name of the parameter.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ParameterDefinitionParameters struct {

	// Definition of the parameter schema. See Parameter Definition Schema below.
	// +kubebuilder:validation:Optional
	Definition []DefinitionParameters `json:"definition,omitempty" tf:"definition,omitempty"`

	// Name of the parameter.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type RestrictionsGeoRestrictionInitParameters struct {

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	// +listType=set
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`

	// Method to restrict distribution of your content by country. Valid values are none, whitelist, and blacklist.
	RestrictionType *string `json:"restrictionType,omitempty" tf:"restriction_type,omitempty"`
}

type RestrictionsGeoRestrictionObservation struct {

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	// +listType=set
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`

	// Method to restrict distribution of your content by country. Valid values are none, whitelist, and blacklist.
	RestrictionType *string `json:"restrictionType,omitempty" tf:"restriction_type,omitempty"`
}

type RestrictionsGeoRestrictionParameters struct {

	// List of ISO 3166-1-alpha-2 country codes for which you want CloudFront either to distribute your content (whitelist) or not distribute your content (blacklist). Required when restriction_type is whitelist or blacklist.
	// +kubebuilder:validation:Optional
	// +listType=set
	Items []*string `json:"items,omitempty" tf:"items,omitempty"`

	// Method to restrict distribution of your content by country. Valid values are none, whitelist, and blacklist.
	// +kubebuilder:validation:Optional
	RestrictionType *string `json:"restrictionType" tf:"restriction_type,omitempty"`
}

type StringSchemaInitParameters struct {

	// Any comments you want to include about the distribution.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Default value for the parameter.
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// Whether the parameter is required.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`
}

type StringSchemaObservation struct {

	// Any comments you want to include about the distribution.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Default value for the parameter.
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// Whether the parameter is required.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`
}

type StringSchemaParameters struct {

	// Any comments you want to include about the distribution.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Default value for the parameter.
	// +kubebuilder:validation:Optional
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// Whether the parameter is required.
	// +kubebuilder:validation:Optional
	Required *bool `json:"required" tf:"required,omitempty"`
}

type TenantConfigInitParameters struct {

	// One or more parameter definitions for the tenant configuration. See Parameter Definition below.
	ParameterDefinition []ParameterDefinitionInitParameters `json:"parameterDefinition,omitempty" tf:"parameter_definition,omitempty"`
}

type TenantConfigObservation struct {

	// One or more parameter definitions for the tenant configuration. See Parameter Definition below.
	ParameterDefinition []ParameterDefinitionObservation `json:"parameterDefinition,omitempty" tf:"parameter_definition,omitempty"`
}

type TenantConfigParameters struct {

	// One or more parameter definitions for the tenant configuration. See Parameter Definition below.
	// +kubebuilder:validation:Optional
	ParameterDefinition []ParameterDefinitionParameters `json:"parameterDefinition,omitempty" tf:"parameter_definition,omitempty"`
}

// MultitenantDistributionSpec defines the desired state of MultitenantDistribution
type MultitenantDistributionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MultitenantDistributionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MultitenantDistributionInitParameters `json:"initProvider,omitempty"`
}

// MultitenantDistributionStatus defines the observed state of MultitenantDistribution.
type MultitenantDistributionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MultitenantDistributionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MultitenantDistribution is the Schema for the MultitenantDistributions API. Provides a CloudFront multi-tenant distribution resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type MultitenantDistribution struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.comment) || (has(self.initProvider) && has(self.initProvider.comment))",message="spec.forProvider.comment is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	Spec   MultitenantDistributionSpec   `json:"spec"`
	Status MultitenantDistributionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MultitenantDistributionList contains a list of MultitenantDistributions
type MultitenantDistributionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MultitenantDistribution `json:"items"`
}

// Repository type metadata.
var (
	MultitenantDistribution_Kind             = "MultitenantDistribution"
	MultitenantDistribution_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MultitenantDistribution_Kind}.String()
	MultitenantDistribution_KindAPIVersion   = MultitenantDistribution_Kind + "." + CRDGroupVersion.String()
	MultitenantDistribution_GroupVersionKind = CRDGroupVersion.WithKind(MultitenantDistribution_Kind)
)

func init() {
	SchemeBuilder.Register(&MultitenantDistribution{}, &MultitenantDistributionList{})
}
