// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ConnectionGroupInitParameters struct {

	// ID of the associated Anycast IP List. ipv6_enabled must not be set to true in order to set this argument
	AnycastIPListID *string `json:"anycastIpListId,omitempty" tf:"anycast_ip_list_id,omitempty"`

	// Whether the connection group is enabled. Default is true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Whether IPv6 is enabled for the connection group. Default is false.
	IPv6Enabled *bool `json:"ipv6Enabled,omitempty" tf:"ipv6_enabled,omitempty"`

	// Name of the connection group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	WaitForDeployment *bool `json:"waitForDeployment,omitempty" tf:"wait_for_deployment,omitempty"`
}

type ConnectionGroupObservation struct {

	// ID of the associated Anycast IP List. ipv6_enabled must not be set to true in order to set this argument
	AnycastIPListID *string `json:"anycastIpListId,omitempty" tf:"anycast_ip_list_id,omitempty"`

	// ARN of the connection group.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// Whether the connection group is enabled. Default is true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Current version of the connection group.
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	// ID of the connection group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether IPv6 is enabled for the connection group. Default is false.
	IPv6Enabled *bool `json:"ipv6Enabled,omitempty" tf:"ipv6_enabled,omitempty"`

	// Whether the connection group is the default connection group for the distribution tenants.
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// Date and time when the connection group was last modified.
	LastModifiedTime *string `json:"lastModifiedTime,omitempty" tf:"last_modified_time,omitempty"`

	// Name of the connection group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The routing endpoint (also known as the DNS name) that is assigned to the connection group, such as d111111abcdef8.cloudfront.net.
	RoutingEndpoint *string `json:"routingEndpoint,omitempty" tf:"routing_endpoint,omitempty"`

	// Current status of the connection group.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	// +mapType=granular
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`

	WaitForDeployment *bool `json:"waitForDeployment,omitempty" tf:"wait_for_deployment,omitempty"`
}

type ConnectionGroupParameters struct {

	// ID of the associated Anycast IP List. ipv6_enabled must not be set to true in order to set this argument
	// +kubebuilder:validation:Optional
	AnycastIPListID *string `json:"anycastIpListId,omitempty" tf:"anycast_ip_list_id,omitempty"`

	// Whether the connection group is enabled. Default is true.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Whether IPv6 is enabled for the connection group. Default is false.
	// +kubebuilder:validation:Optional
	IPv6Enabled *bool `json:"ipv6Enabled,omitempty" tf:"ipv6_enabled,omitempty"`

	// Name of the connection group.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// +kubebuilder:validation:Optional
	WaitForDeployment *bool `json:"waitForDeployment,omitempty" tf:"wait_for_deployment,omitempty"`
}

// ConnectionGroupSpec defines the desired state of ConnectionGroup
type ConnectionGroupSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ConnectionGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConnectionGroupInitParameters `json:"initProvider,omitempty"`
}

// ConnectionGroupStatus defines the observed state of ConnectionGroup.
type ConnectionGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConnectionGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ConnectionGroup is the Schema for the ConnectionGroups API. Provides a CloudFront connection group resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aws}
type ConnectionGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ConnectionGroupSpec   `json:"spec"`
	Status ConnectionGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConnectionGroupList contains a list of ConnectionGroups
type ConnectionGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConnectionGroup `json:"items"`
}

// Repository type metadata.
var (
	ConnectionGroup_Kind             = "ConnectionGroup"
	ConnectionGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ConnectionGroup_Kind}.String()
	ConnectionGroup_KindAPIVersion   = ConnectionGroup_Kind + "." + CRDGroupVersion.String()
	ConnectionGroup_GroupVersionKind = CRDGroupVersion.WithKind(ConnectionGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&ConnectionGroup{}, &ConnectionGroupList{})
}
