// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CertificateInitParameters struct {

	// ARN of the AWS Certificate Manager certificate to use with this distribution tenant.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/acm/v1beta1.Certificate
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("arn",true)
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// Reference to a Certificate in acm to populate arn.
	// +kubebuilder:validation:Optional
	ArnRef *v1.NamespacedReference `json:"arnRef,omitempty" tf:"-"`

	// Selector for a Certificate in acm to populate arn.
	// +kubebuilder:validation:Optional
	ArnSelector *v1.NamespacedSelector `json:"arnSelector,omitempty" tf:"-"`
}

type CertificateObservation struct {

	// ARN of the AWS Certificate Manager certificate to use with this distribution tenant.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type CertificateParameters struct {

	// ARN of the AWS Certificate Manager certificate to use with this distribution tenant.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/acm/v1beta1.Certificate
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("arn",true)
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// Reference to a Certificate in acm to populate arn.
	// +kubebuilder:validation:Optional
	ArnRef *v1.NamespacedReference `json:"arnRef,omitempty" tf:"-"`

	// Selector for a Certificate in acm to populate arn.
	// +kubebuilder:validation:Optional
	ArnSelector *v1.NamespacedSelector `json:"arnSelector,omitempty" tf:"-"`
}

type CustomizationsGeoRestrictionInitParameters struct {

	// Set of ISO 3166-1-alpha-2 country codes for the restriction. Required if restriction_type is whitelist or blacklist.
	// +listType=set
	Locations []*string `json:"locations,omitempty" tf:"locations,omitempty"`

	// Method to restrict distribution by country: none, whitelist, or blacklist.
	RestrictionType *string `json:"restrictionType,omitempty" tf:"restriction_type,omitempty"`
}

type CustomizationsGeoRestrictionObservation struct {

	// Set of ISO 3166-1-alpha-2 country codes for the restriction. Required if restriction_type is whitelist or blacklist.
	// +listType=set
	Locations []*string `json:"locations,omitempty" tf:"locations,omitempty"`

	// Method to restrict distribution by country: none, whitelist, or blacklist.
	RestrictionType *string `json:"restrictionType,omitempty" tf:"restriction_type,omitempty"`
}

type CustomizationsGeoRestrictionParameters struct {

	// Set of ISO 3166-1-alpha-2 country codes for the restriction. Required if restriction_type is whitelist or blacklist.
	// +kubebuilder:validation:Optional
	// +listType=set
	Locations []*string `json:"locations,omitempty" tf:"locations,omitempty"`

	// Method to restrict distribution by country: none, whitelist, or blacklist.
	// +kubebuilder:validation:Optional
	RestrictionType *string `json:"restrictionType,omitempty" tf:"restriction_type,omitempty"`
}

type CustomizationsInitParameters struct {

	// Certificate configuration for the tenant (maximum one).
	Certificate []CertificateInitParameters `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// Geographic restrictions configuration for the tenant (maximum one).
	GeoRestriction []CustomizationsGeoRestrictionInitParameters `json:"geoRestriction,omitempty" tf:"geo_restriction,omitempty"`

	// Web ACL configuration for the tenant (maximum one).
	WebACL []WebACLInitParameters `json:"webAcl,omitempty" tf:"web_acl,omitempty"`
}

type CustomizationsObservation struct {

	// Certificate configuration for the tenant (maximum one).
	Certificate []CertificateObservation `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// Geographic restrictions configuration for the tenant (maximum one).
	GeoRestriction []CustomizationsGeoRestrictionObservation `json:"geoRestriction,omitempty" tf:"geo_restriction,omitempty"`

	// Web ACL configuration for the tenant (maximum one).
	WebACL []WebACLObservation `json:"webAcl,omitempty" tf:"web_acl,omitempty"`
}

type CustomizationsParameters struct {

	// Certificate configuration for the tenant (maximum one).
	// +kubebuilder:validation:Optional
	Certificate []CertificateParameters `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// Geographic restrictions configuration for the tenant (maximum one).
	// +kubebuilder:validation:Optional
	GeoRestriction []CustomizationsGeoRestrictionParameters `json:"geoRestriction,omitempty" tf:"geo_restriction,omitempty"`

	// Web ACL configuration for the tenant (maximum one).
	// +kubebuilder:validation:Optional
	WebACL []WebACLParameters `json:"webAcl,omitempty" tf:"web_acl,omitempty"`
}

type DistributionTenantInitParameters struct {

	// ID of the connection group for the distribution tenant. If not specified, CloudFront uses the default connection group.
	ConnectionGroupID *string `json:"connectionGroupId,omitempty" tf:"connection_group_id,omitempty"`

	// Customizations for the distribution tenant (maximum one).
	Customizations []CustomizationsInitParameters `json:"customizations,omitempty" tf:"customizations,omitempty"`

	// ID of the multi-tenant distribution.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/cloudfront/v1beta1.MultitenantDistribution
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DistributionID *string `json:"distributionId,omitempty" tf:"distribution_id,omitempty"`

	// Reference to a MultitenantDistribution in cloudfront to populate distributionId.
	// +kubebuilder:validation:Optional
	DistributionIDRef *v1.NamespacedReference `json:"distributionIdRef,omitempty" tf:"-"`

	// Selector for a MultitenantDistribution in cloudfront to populate distributionId.
	// +kubebuilder:validation:Optional
	DistributionIDSelector *v1.NamespacedSelector `json:"distributionIdSelector,omitempty" tf:"-"`

	// Set of domains associated with the distribution tenant.
	Domain []DomainInitParameters `json:"domain,omitempty" tf:"domain,omitempty"`

	// Whether the distribution tenant is enabled to serve traffic. Defaults to true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Managed certificate request for CloudFront managed ACM certificate (maximum one).
	ManagedCertificateRequest []ManagedCertificateRequestInitParameters `json:"managedCertificateRequest,omitempty" tf:"managed_certificate_request,omitempty"`

	// Name of the distribution tenant.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Set of parameter values for the distribution tenant.
	Parameter []ParameterInitParameters `json:"parameter,omitempty" tf:"parameter,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// If enabled, the resource will wait for the distribution tenant status to change from InProgress to Deployed. Setting this to false will skip the process. Default: true.
	WaitForDeployment *bool `json:"waitForDeployment,omitempty" tf:"wait_for_deployment,omitempty"`
}

type DistributionTenantObservation struct {

	// ARN of the AWS Certificate Manager certificate to use with this distribution tenant.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// ID of the connection group for the distribution tenant. If not specified, CloudFront uses the default connection group.
	ConnectionGroupID *string `json:"connectionGroupId,omitempty" tf:"connection_group_id,omitempty"`

	// Customizations for the distribution tenant (maximum one).
	Customizations []CustomizationsObservation `json:"customizations,omitempty" tf:"customizations,omitempty"`

	// ID of the multi-tenant distribution.
	DistributionID *string `json:"distributionId,omitempty" tf:"distribution_id,omitempty"`

	// Set of domains associated with the distribution tenant.
	Domain []DomainObservation `json:"domain,omitempty" tf:"domain,omitempty"`

	// Whether the distribution tenant is enabled to serve traffic. Defaults to true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Current version of the distribution tenant.
	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	// ID of the distribution tenant.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Managed certificate request for CloudFront managed ACM certificate (maximum one).
	ManagedCertificateRequest []ManagedCertificateRequestObservation `json:"managedCertificateRequest,omitempty" tf:"managed_certificate_request,omitempty"`

	// Name of the distribution tenant.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Set of parameter values for the distribution tenant.
	Parameter []ParameterObservation `json:"parameter,omitempty" tf:"parameter,omitempty"`

	// Current status of the distribution tenant.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	// +mapType=granular
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`

	// If enabled, the resource will wait for the distribution tenant status to change from InProgress to Deployed. Setting this to false will skip the process. Default: true.
	WaitForDeployment *bool `json:"waitForDeployment,omitempty" tf:"wait_for_deployment,omitempty"`
}

type DistributionTenantParameters struct {

	// ID of the connection group for the distribution tenant. If not specified, CloudFront uses the default connection group.
	// +kubebuilder:validation:Optional
	ConnectionGroupID *string `json:"connectionGroupId,omitempty" tf:"connection_group_id,omitempty"`

	// Customizations for the distribution tenant (maximum one).
	// +kubebuilder:validation:Optional
	Customizations []CustomizationsParameters `json:"customizations,omitempty" tf:"customizations,omitempty"`

	// ID of the multi-tenant distribution.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/cloudfront/v1beta1.MultitenantDistribution
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DistributionID *string `json:"distributionId,omitempty" tf:"distribution_id,omitempty"`

	// Reference to a MultitenantDistribution in cloudfront to populate distributionId.
	// +kubebuilder:validation:Optional
	DistributionIDRef *v1.NamespacedReference `json:"distributionIdRef,omitempty" tf:"-"`

	// Selector for a MultitenantDistribution in cloudfront to populate distributionId.
	// +kubebuilder:validation:Optional
	DistributionIDSelector *v1.NamespacedSelector `json:"distributionIdSelector,omitempty" tf:"-"`

	// Set of domains associated with the distribution tenant.
	// +kubebuilder:validation:Optional
	Domain []DomainParameters `json:"domain,omitempty" tf:"domain,omitempty"`

	// Whether the distribution tenant is enabled to serve traffic. Defaults to true.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Managed certificate request for CloudFront managed ACM certificate (maximum one).
	// +kubebuilder:validation:Optional
	ManagedCertificateRequest []ManagedCertificateRequestParameters `json:"managedCertificateRequest,omitempty" tf:"managed_certificate_request,omitempty"`

	// Name of the distribution tenant.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Set of parameter values for the distribution tenant.
	// +kubebuilder:validation:Optional
	Parameter []ParameterParameters `json:"parameter,omitempty" tf:"parameter,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// If enabled, the resource will wait for the distribution tenant status to change from InProgress to Deployed. Setting this to false will skip the process. Default: true.
	// +kubebuilder:validation:Optional
	WaitForDeployment *bool `json:"waitForDeployment,omitempty" tf:"wait_for_deployment,omitempty"`
}

type DomainInitParameters struct {

	// Set of domains associated with the distribution tenant.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`
}

type DomainObservation struct {

	// Set of domains associated with the distribution tenant.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// Current status of the distribution tenant.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type DomainParameters struct {

	// Set of domains associated with the distribution tenant.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain" tf:"domain,omitempty"`
}

type ManagedCertificateRequestInitParameters struct {

	// Certificate transparency logging preference. Valid values: enabled, disabled.
	CertificateTransparencyLoggingPreference *string `json:"certificateTransparencyLoggingPreference,omitempty" tf:"certificate_transparency_logging_preference,omitempty"`

	// Primary domain name for the certificate.
	PrimaryDomainName *string `json:"primaryDomainName,omitempty" tf:"primary_domain_name,omitempty"`

	// Host for validation token. Valid values: cloudfront, domain.
	ValidationTokenHost *string `json:"validationTokenHost,omitempty" tf:"validation_token_host,omitempty"`
}

type ManagedCertificateRequestObservation struct {

	// Certificate transparency logging preference. Valid values: enabled, disabled.
	CertificateTransparencyLoggingPreference *string `json:"certificateTransparencyLoggingPreference,omitempty" tf:"certificate_transparency_logging_preference,omitempty"`

	// Primary domain name for the certificate.
	PrimaryDomainName *string `json:"primaryDomainName,omitempty" tf:"primary_domain_name,omitempty"`

	// Host for validation token. Valid values: cloudfront, domain.
	ValidationTokenHost *string `json:"validationTokenHost,omitempty" tf:"validation_token_host,omitempty"`
}

type ManagedCertificateRequestParameters struct {

	// Certificate transparency logging preference. Valid values: enabled, disabled.
	// +kubebuilder:validation:Optional
	CertificateTransparencyLoggingPreference *string `json:"certificateTransparencyLoggingPreference,omitempty" tf:"certificate_transparency_logging_preference,omitempty"`

	// Primary domain name for the certificate.
	// +kubebuilder:validation:Optional
	PrimaryDomainName *string `json:"primaryDomainName,omitempty" tf:"primary_domain_name,omitempty"`

	// Host for validation token. Valid values: cloudfront, domain.
	// +kubebuilder:validation:Optional
	ValidationTokenHost *string `json:"validationTokenHost,omitempty" tf:"validation_token_host,omitempty"`
}

type ParameterInitParameters struct {

	// Name of the distribution tenant.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Value of the parameter.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ParameterObservation struct {

	// Name of the distribution tenant.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Value of the parameter.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ParameterParameters struct {

	// Name of the distribution tenant.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Value of the parameter.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type WebACLInitParameters struct {

	// Action to take for the web ACL. Valid values: allow, block.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// ARN of the AWS Certificate Manager certificate to use with this distribution tenant.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/wafv2/v1beta1.WebACL
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("arn",true)
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// Reference to a WebACL in wafv2 to populate arn.
	// +kubebuilder:validation:Optional
	ArnRef *v1.NamespacedReference `json:"arnRef,omitempty" tf:"-"`

	// Selector for a WebACL in wafv2 to populate arn.
	// +kubebuilder:validation:Optional
	ArnSelector *v1.NamespacedSelector `json:"arnSelector,omitempty" tf:"-"`
}

type WebACLObservation struct {

	// Action to take for the web ACL. Valid values: allow, block.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// ARN of the AWS Certificate Manager certificate to use with this distribution tenant.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type WebACLParameters struct {

	// Action to take for the web ACL. Valid values: allow, block.
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// ARN of the AWS Certificate Manager certificate to use with this distribution tenant.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/wafv2/v1beta1.WebACL
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("arn",true)
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// Reference to a WebACL in wafv2 to populate arn.
	// +kubebuilder:validation:Optional
	ArnRef *v1.NamespacedReference `json:"arnRef,omitempty" tf:"-"`

	// Selector for a WebACL in wafv2 to populate arn.
	// +kubebuilder:validation:Optional
	ArnSelector *v1.NamespacedSelector `json:"arnSelector,omitempty" tf:"-"`
}

// DistributionTenantSpec defines the desired state of DistributionTenant
type DistributionTenantSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DistributionTenantParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DistributionTenantInitParameters `json:"initProvider,omitempty"`
}

// DistributionTenantStatus defines the observed state of DistributionTenant.
type DistributionTenantStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DistributionTenantObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DistributionTenant is the Schema for the DistributionTenants API. Provides a CloudFront distribution tenant resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aws}
type DistributionTenant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   DistributionTenantSpec   `json:"spec"`
	Status DistributionTenantStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DistributionTenantList contains a list of DistributionTenants
type DistributionTenantList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DistributionTenant `json:"items"`
}

// Repository type metadata.
var (
	DistributionTenant_Kind             = "DistributionTenant"
	DistributionTenant_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DistributionTenant_Kind}.String()
	DistributionTenant_KindAPIVersion   = DistributionTenant_Kind + "." + CRDGroupVersion.String()
	DistributionTenant_GroupVersionKind = CRDGroupVersion.WithKind(DistributionTenant_Kind)
)

func init() {
	SchemeBuilder.Register(&DistributionTenant{}, &DistributionTenantList{})
}
